apiVersion: apps/v1
kind: Deployment
metadata:
  name: battlefield-ui
  labels:
    app: battlefield-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: battlefield-ui
  template:
    metadata:
      labels:
        app: battlefield-ui
    spec:
      containers:
      - name: main
        image: quay.io/bszeti/battlefield-ui
        env:
        - name: NAMESPACE
          value: visual
        ports:
        - containerPort: 8080
