apiVersion: v1
kind: Service
metadata:
  labels:
    app: battlefield-ui
  name: battlefield-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: battlefield-ui
  type: ClusterIP
status:
  loadBalancer: {}
