apiVersion: rhte.demojam.battlefield/v1alpha1
kind: Battlefield
metadata:
  Name: defaultName
spec:
  duration: 180
  hitFrequency: 2
  players:
  - name: player0
    image: quay.io/bszeti/battlefield-player-fuse:latest
    maxhealth: 20
    shield: false
    disqualified: false
  - name: player1
    image: quay.io/bszeti/battlefield-player-fuse:latest
    maxhealth: 20
    shield: false
    disqualified: false
  - name: player2
    image: quay.io/bszeti/battlefield-player-fuse:latest
    maxhealth: 20
    shield: false
    disqualified: false
  - name: player3
    image: quay.io/bszeti/battlefield-player-fuse:latest
    maxhealth: 20
    shield: false
    disqualified: false
